title: Edisson López
logo: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
#description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
